name: geefetch

channels:
  - conda-forge
  - defaults

# the purpose of this file is to:
# specify the python version & install non-pip dependencies
dependencies:
  - python >=3.11, <3.12
  - gdal >=3.9, <3.10
  - pip==24.2
  - rasterio >=1.3, <1.4
