data_dir: ~/data/landes-3
satellite_default:
  resolution: 10
  tile_size: 1_000
  dtype: UInt16
  composite_method: MEDIAN
  aoi:
    spatial:
      left: 410000
      right: 410500
      bottom: 6351000
      top: 6351500
      epsg: 2154 # Lambert 93
    temporal:
      start_date: 2020-01-01
      end_date: 2020-12-31
    country: France
  gee:
    ee_project_id: geefetch
    max_tile_size: 5 # in MB
s1:
  composite_method: MEAN
s2: {}
gedi: 
  format: PARQUET
