name: default

on:
  # run when pr on main branch
  pull_request:
    branches: [ "main" ]

jobs:
  pre-commit_and_changelog:
    name: pre-commit_and_changelog
    runs-on: ubuntu-latest
    defaults:  # this is necessary
      run:
        shell: bash -l {0}
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: run pre-commit
        uses: pre-commit/action@v3.0.1
      - name: check changelog
        uses: tarides/changelog-check-action@v2
        with:
          changelog: CHANGELOG.md

  install_and_test:
    name: install_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: install and test
        uses: ./.github/actions/install_and_test